CREATE TABLE [Majors]
(
	[MajorID] INT PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(50) NOT NULL
);

CREATE TABLE [Subjects]
(
	[SubjectID] INT PRIMARY KEY IDENTITY(101, 1),
	[SubjectName] NVARCHAR(50) NOT NULL,
);

CREATE TABLE [Students]
(
	[StudentID] INT PRIMARY KEY IDENTITY(1, 1),
	[StudentNumber] NVARCHAR(50) NOT NULL,
	[StudentName] NVARCHAR(50) NOT NULL,
	[MajorID] INT FOREIGN KEY REFERENCES [Majors]([MajorID]) NOT NULL
);

CREATE TABLE [Payments]
(
	[PaymentID] INT PRIMARY KEY IDENTITY(1001, 1),
	[PaymentDate] DATE NOT NULL,
	[PaymentAmount] DECIMAL(10, 2) NOT NULL,
	[StudentID] INT FOREIGN KEY REFERENCES [Students]([StudentID]) NOT NULL
);

CREATE TABLE [Agenda]
(	
	[StudentID] INT FOREIGN KEY REFERENCES [Students]([StudentID]) NOT NULL,
	[SubjectID] INT FOREIGN KEY REFERENCES [Subjects]([SubjectID]) NOT NULL
	PRIMARY KEY ([StudentID], [SubjectID])
);